### PR TITLE
Proposal to rename the skills of the DrivingSkill

### LINKED ISSUE #3774: Rename advanced_driving to driving
**Describe the bug**
We have an `advanced_driving` skill in GAMA 1.9.1, but no (more) `driving` skill. Since the previous one is not part of GAMA anymore, we could perhaps get rid of the `advanced_` ? 

(Making `driving` a new skill, subclass in Java of the previous, should be enough).

### PR DESCRIPTION
**Pull request by AlexisDrogoul**
Proposal to rename the skills of the DrivingSkill

### CODE REVIEW

**Comment by RoiArthurB** [comment]
As I pointed in the issue, regardless of the quality of the work, I think it would be better to keep this PR for GAMA 2 and limit as much as possible GAML redefinition. 

I understand the confusion that "advanced driving skill" implies, but it would break retro-compatibility and stuff, which I would prefer to preserve in the maintenance mode GAMA 1.9.X  is now.

**Comment by AlexisDrogoul** [comment]
To be fair, it doesn't break retrocompatibility as the previous names are still lying around and can be still used. Only thing to verify would be that models with `road` and `intersection` species do not confuse these with the skills.

**Comment by AlexisDrogoul** [comment]
At the very least, to be 100% sure, we can rename the `road` and `intersection` skills to `road_skill` and `intersection_skill` so that we are sure it will not be confused with species. But having some proper english syntax construction wouldn't hurt (instead of `skill_road` : the road of skills ! `skill_road_node` : the node of the road of skills ?? 🤔🙄)

**Comment by AlexisDrogoul** [comment]
@ptaillandier @minhduc0711 @RoiArthurB ok with the changes ? As a reminder, they will remain optional (i.e. the old names are still available).

**Comment by ptaillandier** [comment]
I am ok with it.

**Pull request merged**
