### PR TITLE
fix(headless): run with arguments from GAMA.ini

### PR DESCRIPTION
**Pull request by WoodenMaiden**
cf. #3864

### CODE REVIEW

**Comment by RoiArthurB** [comment]
@lesquoyb can you test and review the Windows update ? (I'll test later macos/linux and update PR to proper files)

**Comment by lesquoyb** [comment]
Just tested on windows and it works properly

**Comment by lesquoyb** [comment]
Also seems like it fixes #3867

**Comment by RoiArthurB** [comment]
@WoodenMaiden could you extend a little this PR for windows reading the default JVM `memory` variable gathered from Gama.ini if not set by command line, please ? :)

**Review by lesquoyb — APPROVED** [review]

**Pull request merged**
